ValueSet: BreastCancerICD10
Title: "Breast Cancer ICD-10 ValueSet"
Description: "This ValueSet includes ICD-10 codes for breast cancer."
* $ICD10CM#C50.011 "Malignant neoplasm of nipple and areola, right female breast"
* $ICD10CM#C50.012 "Malignant neoplasm of nipple and areola, left female breast"
* $ICD10CM#C50.019 "Malignant neoplasm of nipple and areola, unspecified female breast"
* $ICD10CM#C50.111 "Malignant neoplasm of central portion of right female breast"
* $ICD10CM#C50.112 "Malignant neoplasm of central portion of left female breast"
* $ICD10CM#C50.119 "Malignant neoplasm of central portion of unspecified female breast"
* $ICD10CM#C50.211 "Malignant neoplasm of upper-inner quadrant of right female breast"
* $ICD10CM#C50.212 "Malignant neoplasm of upper-inner quadrant of left female breast"
* $ICD10CM#C50.219 "Malignant neoplasm of upper-inner quadrant of unspecified female breast"
* $ICD10CM#C50.311 "Malignant neoplasm of lower-inner quadrant of right female breast"
* $ICD10CM#C50.312 "Malignant neoplasm of lower-inner quadrant of left female breast"
* $ICD10CM#C50.319 "Malignant neoplasm of lower-inner quadrant of unspecified female breast"
* $ICD10CM#C50.411 "Malignant neoplasm of upper-outer quadrant of right female breast"
* $ICD10CM#C50.412 "Malignant neoplasm of upper-outer quadrant of left female breast"
* $ICD10CM#C50.419 "Malignant neoplasm of upper-outer quadrant of unspecified female breast"
* $ICD10CM#C50.511 "Malignant neoplasm of lower-outer quadrant of right female breast"
* $ICD10CM#C50.512 "Malignant neoplasm of lower-outer quadrant of left female breast"
* $ICD10CM#C50.519 "Malignant neoplasm of lower-outer quadrant of unspecified female breast"
* $ICD10CM#C50.611 "Malignant neoplasm of axillary tail of right female breast"
* $ICD10CM#C50.612 "Malignant neoplasm of axillary tail of left female breast"
* $ICD10CM#C50.619 "Malignant neoplasm of axillary tail of unspecified female breast"
* $ICD10CM#C50.811 "Malignant neoplasm of overlapping sites of right female breast"
* $ICD10CM#C50.812 "Malignant neoplasm of overlapping sites of left female breast"
* $ICD10CM#C50.819 "Malignant neoplasm of overlapping sites of unspecified female breast"
* $ICD10CM#C50.911 "Malignant neoplasm of unspecified site of right female breast"
* $ICD10CM#C50.912 "Malignant neoplasm of unspecified site of left female breast"
* $ICD10CM#C50.919 "Malignant neoplasm of unspecified site of unspecified female breast"

ValueSet: TumorStatusVS
Title: "Tumor Status ValueSet"
Description: "This ValueSet includes codes for tumor status."
* $LOINC#LA6577-6 "Negative"
* $LOINC#LA6576-8 "Positive"